services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: webapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d webapi"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "5050:80"
    depends_on:
      - postgres

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapicrud
    restart: always
    ports:
      - "7066:7066"
      - "5020:5020"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=webapi;Username=admin;Password=secret
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  postgres_data:
  